# shell IDE
#   docker-compose up -d
# url: localhost:8080
#   initialAdminPassword
#     shell container
#       cat /var/jenkins_home/secrets/initialAdminPassword
#   credentials:
#     jenkins/jenkins

services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
#  ssh-agent:
#    image: jenkins/ssh-agent
volumes:
  jenkins_home:
